#!/bin/bash

set -euop pipefail
# si il y a une erreur, ou qu'une variable n'est pas definie, ou que le chemin n'est pas bien defini, ou si un pipe a un probleme il va s'arreter tout de suite


## Cluster utilise:
cluster="Slurm"

if [ "${cluster}" == "Torq" ]
then

## bout de code d'Emilie qui permet de faire fonctionner mon conda
##source /home/emilie.drouineau/.bashrc
  if [ -f "/home/marina.nocente/miniconda2/etc/profile.d/conda.sh" ]; then
      . "/home/marina.nocente/miniconda2/etc/profile.d/conda.sh"
      CONDA_CHANGEPS1=false conda activate
  fi

else [ "${cluster}" != "Torq" ]
  echo "Ce n'est pas un cluster Torq"
fi

## Activation de conda
conda activate fastqScreen

## Affichage de "start fastqScreen" pour verifier que le script se lance bien
echo "start fastqScreen"


fastq_screen ${fastqFile} --threads 1 --conf ${fastqScreenConf} --outdir ${outputDir}


## Affichage de "done fastqcScreen" pour verifier que le script s est bien termine
echo "done fastqcScreen"


## Parametres de fastqScreen:
# ${fastqFile} : le fichier a analyser avec son chemin
# --threads 8 : nombre de threads utilisés
# --conf ${fastqScreenConf} : fichier de configuration de fastqScreen a utiliser
# --outdir ${outputDir} : repertoire de sortie des resultats de fastqScreen

# https://www.bioinformatics.babraham.ac.uk/projects/fastq_screen/fastq_screen_documentation.html
