#!/bin/bash

set -euop pipefail
# si il y a une erreur, ou qu'une variable n'est pas definie, ou que le chemin n'est pas bien defini, ou si un pipe a un probleme il va s'arreter tout de suite


## Cluster utilise:
cluster="Slurm"

if [ "${cluster}" == "Torq" ]
then

## bout de code d'Emilie qui permet de faire fonctionner mon conda
##source /home/emilie.drouineau/.bashrc
  if [ -f "/home/marina.nocente/miniconda2/etc/profile.d/conda.sh" ]; then
      . "/home/marina.nocente/miniconda2/etc/profile.d/conda.sh"
      CONDA_CHANGEPS1=false conda activate
  fi

else [ "${cluster}" != "Torq" ]
  echo "Ce n'est pas un cluster Torq"
fi


### Activation de l environnement samtools (car ouverture d'un sous-shell):
conda activate samtools

### Lancement de samtools flagstat :
echo "start samtools flagstat"

echo "${bamFile}"
ech "${outputDir}"

samtools flagstat ${bamFile} > "${outputDir}${bamFile##*/}_flagstat.txt"


echo "done samtools flagstat"


### Explication des options choisies:
# > : pour indiquer un fichier de sortie

### samtools flagstat permet d obtenir :
# total : nombre total de reads (somme des reads forward, reverse, single et supplémentaires).
#supplementary : nombre de fois où un read chimerique a mappé à plusieurs endroits.
# mapped : nombre de reads qui ont mappé sur les contigs et pourcentage mappés sur le total.
# paired in sequence : somme des reads 1 et 2
# properly paired : nombre de reads forward et reverse qui ont mappés sur les même contigs orientés l’un vers l’autre.
# with itself and mate mapped : nombre de reads appariés où les deux sont mappés.
# singletons : nombre de reads appariés où l’un est mappé et pas l’autre.
