#!/bin/bash

set -euop pipefail
# si il y a une erreur, ou qu'une variable n'est pas definie, ou que le chemin n'est pas bien defini, ou si un pipe a un probleme il va s'arreter tout de suite


## Cluster utilise:
cluster="Slurm"

if [ "${cluster}" == "Torq" ]
then

## bout de code d'Emilie qui permet de faire fonctionner mon conda
##source /home/emilie.drouineau/.bashrc
  if [ -f "/home/marina.nocente/miniconda2/etc/profile.d/conda.sh" ]; then
      . "/home/marina.nocente/miniconda2/etc/profile.d/conda.sh"
      CONDA_CHANGEPS1=false conda activate
  fi

else [ "${cluster}" != "Torq" ]
  echo "Ce n'est pas un cluster Torq"
fi

## Definition du repertoire de sortie pour les resultats:
outputDir="/home/mnocente/Bureau/Projet_ChIP_Marina/scripts/samtools-index_bam/results"

### Affichage de "start samtools" pour verifier que le script se lance bien
echo "start samtools"

### Activation de conda pour samtools
conda activate samtools


samtools index ${bamFile} -b "${outputDir}indexed_${bamFile##*/}.bai"


echo "end samtools"
