#!/bin/bash

set -euop pipefail
# si il y a une erreur, ou qu'une variable n'est pas definie, ou que le chemin n'est pas bien defini, ou si un pipe a un probleme il va s'arreter tout de suite


## Cluster utilise:
cluster="Slurm"

if [ "${cluster}" == "Torq" ]
then

## bout de code d'Emilie qui permet de faire fonctionner mon conda
##source /home/emilie.drouineau/.bashrc
  if [ -f "/home/marina.nocente/miniconda2/etc/profile.d/conda.sh" ]; then
      . "/home/marina.nocente/miniconda2/etc/profile.d/conda.sh"
      CONDA_CHANGEPS1=false conda activate
  fi

else [ "${cluster}" != "Torq" ]
  echo "Ce n'est pas un cluster Torq"
fi


## Activation de conda
conda activate fastqc

## Affichage de "start fastqc" pour verifier que le script se lance bien
echo "start fastqc"

## Affichage du fichier fastq qui va etre traite par fastQC:
echo "${fastqFile}"

## Lancement de fastQC :
fastqc "${fastqFile}" -t 1 -outdir "${outputDir}"

## Explication des parametres utilises:
# ${fastqFile} : la liste des fichiers fastq
# -t : nombre de threads utilises
# -outdir : le chemin du repertoire qui contiendra les resultats de fastQC


## Affichage de "done fastqc" pour verifier que le script s est bien termine
echo "done fastqc"
